# Generated by Django 2.0.4 on 2018-04-19 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180418_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookToAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Author')),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.AddField(
            model_name='booktoauthor',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Book'),
        ),
        migrations.AlterUniqueTogether(
            name='booktoauthor',
            unique_together={('author', 'book')},
        ),
    ]
