# Generated by Django 2.0.4 on 2018-04-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180420_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='brief',
            field=models.TextField(editable=False, verbose_name='课程简介'),
        ),
    ]
